### ISSUE TITLE
Move dependencies => peerDependencies

### ISSUE THREAD

**Issue by nybblr** [cif/redux-fusion#1]
I love this approach and am experimenting with it in my own apps. However, `dependencies` should be switched to `peerDependencies` and and the versioning should be much more lenient. At the moment, `combineLatest` and friends don't seem to work when I just add `redux-fusion` to my `package.json`. Things seem to work though if I copy-paste the redux-fusion source into my codebase.

**Comment by cif** [comment]
Are you getting an null props$ argument?  

I tried to use this in a React Native project last week and had that issue. Unfortunately, I didn't have time to look into a fix.

Glad you like the idea, it's a simple HOC design theory at this point. I am hoping to improve upon it, PR's 100% welcome

**Comment by nybblr** [comment]
Ah yep that's probably what I was happening. Would love to PR a fix! I'll finish up some work then try swapping in a fork with fixes.

RE example, not quite yet, but I will likely have some fragments I can extract. When I get some nice ones, I will definitely send 'em here!

**Comment by cif** [comment]
Great keep me posted!. Next free time block isn't for a couple weeks if you have some luck before me then PR it up!

I also made your suggested deps changes:
https://github.com/cif/redux-fusion/commit/5c684fd2ef90e3c4b8220dc8879cba1a205e0aa2

**Comment by nybblr** [comment]
Sweet! I'll give that commit a shot. Heads up, the `~` is really specific (semantic, so it targets the latest patch version), so it can't use say RxJS 5.4.0 that's out right now. So perhaps stick with the `^` for RxJS and React, and give a range for Recompose since it hasn't reached a major version?

**Comment by cif** [comment]
Yep, OK totally botched that thanks for catch. Re read docs on peerDeps and updated.

**Comment by nybblr** [comment]
Haha, I just discovered peerDeps as of yesterday trying to get https://github.com/nybblr/firehoce out.

I'm having trouble with `yarn build` locally, complaining about not having `npm-install-peers`? Also IIRC, you don't want to duplicate peerDeps to dependencies (latest commit), right?

**Comment by cif** [comment]
Honestly, I just spent the last 20 min trying to figure this out... I can't build locally or on CI without "dependencies" specified as install won't install them.  

I *think* you do want both, that way it will first try to resolve the peerDependencies higher up the hierarchy when you're bundling and install if they aren't there...  ?? https://codingwithspike.wordpress.com/2016/01/21/dealing-with-the-deprecation-of-peerdependencies-in-npm-3/

**Comment by nybblr** [comment]
Oh, I didn't know that. Hmm, here's a shot in the dark:

- Remove dependencies and just use peerDependencies
- Add a `peers` script like you had before, but don't invoke it from any of the other scripts (like build)
- For your CI, do `npm run peers && npm run build`
- For local dev, I think Babel should be okay with missing packages?

**Comment by cif** [comment]
The peers script was a lost cause: This didn't work locally or on CI https://www.npmjs.com/package/npm-install-peers

**Comment by nybblr** [comment]
So in NPM 3 I guess: you're supposed to just use dependencies (very leniently, since it flattens modules) and make sure the build tool doesn't try to include the modules?

**Comment by cif** [comment]
That's how I understood it. Seems to make sense, I was looking in node_modules as I was playing with `package.json`

**Comment by nybblr** [comment]
Ooo, now I've got a bunch of repos to fix :D

**Comment by nybblr** [comment]
Good news: using your latest commit, the versioning worked great with Yarn (didn't change the versions of React/Recompose/RxJS I had installed). Seems to be working!

**Comment by cif** [comment]
Closing this issue, let's open another one to track any problems with the HOC itself as mentioned earlier in the thread.

**Comment by nybblr** [comment]
:+1: thanks @cif! I'm not getting the error now, so I guess it had something to do with an older combo of Recompose + RxJS.

**Comment by cif** [comment]
Nice! Curious, what versions of those three deps are you running in your
main package?

**Comment by nybblr** [comment]
Here are the resolutions from my `yarn.lock`:

- rxjs: 5.4.0
- react: 15.5.4
- recompose: 0.23.1
