### ISSUE TITLE
Component remounts with react-router

### ISSUE THREAD

**Issue by adithep** [cif/redux-fusion#2]
Hi,

I am experimenting with this approach and finding that components always unmount and remount when I sue fuse(stream$)(component) with react-router as oppose to connect(mapStateToProp, MapDispatchToProp)(component) where when you push a new route it doesn't remount.

Is there a way to around this behavior?

**Comment by cif** [comment]
Interesting. Are you able to post some example code? At what point in component hierarchy are you wrapping with `fuse()`? 

The times I that I have used react-router mounting and unmounting was intended behaviour (e.g. new route = new render) but sounds like that might not be your case. 

I will do some more research on this, but I am curious if using `createElement()` in HOC might be the difference vs connect().

**Comment by cif** [comment]
Looks like `connect` also uses createElement for HOC https://github.com/reactjs/react-redux/blob/master/src/components/connectAdvanced.js#L256

**Comment by cif** [comment]
Great find! That totally makes sense. I applied the changes in your PR locally but made sure to keep tests working and error handling in place. Your changes have been published to NPM as well. `+ redux-fusion@0.1.9` 

Let me know if everything seems to be working and will close out the PR/issue

**Comment by adithep** [comment]
All working! Thanks!
