### ISSUE TITLE
Stream of component life cycle event.

### ISSUE THREAD

**Issue by mapkuff** [cif/redux-fusion#7]
IMHO, if we have stream of component life cycle events. it's gonna make fusion more powerful.
for example, takeUntil componentWillUnmount.

     something$
        .map(someMappingOperation)
        .thisAndThat()
        .takeUntil(lifeCycle.of('componentWillUnmount'));

or we can start doing something when componentDidMount.

    lifeCycle
       .of('componentDidMount')
       .mergeMap(Observable.interval(1000))
       .thisAndThat();

**Comment by cif** [comment]
I could see that being useful. Any high level suggestions on implementation? Wonder if React provides something cleaner than declaring lifecycle methods in the HOC and having them act as pass thru observables to the "fuser" function.  PRs are of course welcome as well

**Comment by cif** [comment]
Closing this due to age, labeling as possible enhancement for future
